---
- block: # Set root password and store it in passwordstore (see passwordstore.org)

  - name: 'Generate new root pass and add to passwordstore'
    local_action: shell {{ role_path }}/scripts/gen_pwstore_mline_entry.sh | pass insert --force --multiline servers/{{ inventory_hostname }}/root

  - name: 'Set root password from passwordstore'
    user:
      name: root
      password: "{{ lookup('passwordstore', 'servers/{{ inventory_hostname }}/root subkey=hash')}}"
      update_password: always

  tags:
    - rootpass

#  when:
#    - setrootpass is defined
#    - setrootpass == 'True'